TARGET = "PV1MATH"
MISSING_VALUES_THRESHOLD = 70.0
TEST_SIZE = 0.20
RANDOM_STATE = 7
KNN_NEIGHBORS = 8
MMINS_CAP = 450
VARIANCE_THRESHOLD = 0.0

CATEGORICAL_COLS = ["ST004D01T", "SCHLTYPE"]
ORDINAL_COLS = ["ST062Q01TA", "REPEAT", "IMMIG"]

DATA_DIR = "data"
DATASET_DIR = "dataset"