import numpy as np
import pandas as pd
import shap
from scipy.stats import kendalltau, spearmanr

def rashomon_set_builder(model_training_all_results_dic, k_nbr_of_features_chosen, task: str = 'regression', rashomon_threshold: float = 0.05):
    """
    Constructs a Rashomon set from the model training all_results dictionary for a given k.

    Arguments:
     - model_training_all_results_dic (dict): A dictionary containing the (regression or classification) results of the model training phase, generated by the evaluate_k_values() function.
     - k_nbr_of_features_chosen (int): The number of features for which to select the models (either 5, 10, 15 or 20).
     - task (str, optional): The task type, either 'regression' or 'classification'. Defaults to 'regression'.
     - rashomon_threshold (float, optional): The performance drop tolerance for a model to be included in the Rashomon set. Default set to 0.05.

    Returns:
     - dict: A dictionary containing the selected models for the Rashomon set.
    """

    if model_training_all_results_dic is None or not isinstance(model_training_all_results_dic, dict):
        raise ValueError("model_training_all_results_dic must be a valid dictionary.")

    if task not in ['regression', 'classification']:
        raise ValueError("Invalid task. Task must be 'regression' or 'classification'.")

    if rashomon_threshold < 0:
        raise ValueError("rashomon_threshold must be non-negative.")

    if k_nbr_of_features_chosen not in model_training_all_results_dic:
        raise ValueError(f"No results found for k = {k_nbr_of_features_chosen} in the dictionary.")

    results_k = model_training_all_results_dic[k_nbr_of_features_chosen]['results']
    
    model_scores = {}
    for model_name, result in results_k.items():
        score = result.get('best_cv_score')
        if score is not None:
            model_scores[model_name] = score

    if not model_scores:
        raise ValueError(f"No CV scores found for k = {k_nbr_of_features_chosen}.")

    best_score = max(model_scores.values())
    
    # Absolute threshold aligned with the project proposal (Delta <= 0.05)
    lowest_score_acceptable = best_score - rashomon_threshold

    rashomon_set_dict = {}
    
    for model_name, score in model_scores.items():
        if score >= lowest_score_acceptable:
            rashomon_set_dict[model_name] = results_k[model_name]

    metric_label = "best R² CV score" if task == 'regression' else "best F1 macro CV score"
    
    print(f"\n{'='*60}")
    print(f"RASHOMON SET CONSTRUCTION (k={k_nbr_of_features_chosen}, Task={task})")
    print(f"{'='*60}")
    print(f"\nBest CV Score achieved : {best_score:.4f}")
    print(f"Acceptable threshold   : >= {lowest_score_acceptable:.4f} (Δ <= {rashomon_threshold})")
    print(f"\nRashomon set contains the following models:")
    print()
    for model_name, res_dict in rashomon_set_dict.items():
        score = res_dict.get('best_cv_score')
        print(f"  • {model_name:<10} : {metric_label} = {score:.4f}")
        
    print(f"\n{'='*60}\n")

    return rashomon_set_dict

def local_and_global_shap_values_calculator(rashomon_set_dict, X_train, X_test, feature_names, task='regression'):
    """
    Calculates local and global SHAP values for each model in the Rashomon set.

    Arguments:
    - rashomon_set_dict (dict): A dictionary of models in the Rashomon set, from rashomon_set_builder().
    - X_train (pd.DataFrame): The training data adapted to the selected features.
    - X_test (pd.DataFrame): The test data adapted to the selected features.
    - feature_names (list): A list of feature names.
    - task (str, optional): The task type, only calibrated for regression tasks as the best rashomon set focus on regression models. Defaults to 'regression'. "classification" is not supported.

    Returns:
    - tuple: A tuple containing two dictionaries: one for global SHAP rankings and one for individual SHAP values for each model.

    """

    # INSPIRATION: - https://stackoverflow.com/questions/72599807/how-to-extract-the-most-important-features-from-a-ml-model-using-shap-why-are 
    #              - https://www.geeksforgeeks.org/machine-learning/shap-with-a-linear-svc-model-from-sklearn-using-pipeline/
    
    global_mean_absolute_shap_rankings = {}
    individual_shap_values_for_every_model = {}

    for model_name, results in rashomon_set_dict.items():

        model_grid_search = results['model']
        best_estimator = model_grid_search.best_estimator_

        if task == 'regression':

            if model_name == "LR":
                scaler = best_estimator.named_steps.get('scaler', None)
                X_train_for_shap = scaler.transform(X_train) if scaler else X_train
                X_test_for_shap = scaler.transform(X_test) if scaler else X_test
                explainer = shap.LinearExplainer(best_estimator.named_steps['model'], X_train_for_shap, feature_perturbation="correlation_dependent") # helps keeping realism in profile computation by computing "smart" conditional expectations. SOURCE: https://shap.readthedocs.io/en/latest/example_notebooks/tabular_examples/linear_models/Math%20behind%20LinearExplainer%20with%20correlation%20feature%20perturbation.html 
                shap_values = explainer.shap_values(X_test_for_shap)

            elif model_name == "RF" or model_name == "XGBoost":
                explainer = shap.TreeExplainer(best_estimator.named_steps['model'])
                shap_values = explainer.shap_values(X_test)

            elif model_name == "SVR":

                #Background_sample and X_test_sample processes are required to limit the computational cost of this operation.
                # shap.kmeans() is preferred over shap.sample() as it selects better representative data points.
                max_samples = 30 

                if X_test.shape[0] > max_samples:

                    if hasattr(X_test, "sample"):
                        X_test_sample = X_test.sample(n=max_samples, random_state=7)

                    else:
                        indices = np.random.choice(X_test.shape[0], size=max_samples, replace=False)
                        X_test_sample = X_test[indices]
                else:
                    X_test_sample = X_test
                    
                scaler = best_estimator.named_steps.get('scaler', None)
                X_train_for_shap= scaler.transform(X_train) if scaler else X_train
                X_test_for_shap = scaler.transform(X_test_sample) if scaler else X_test_sample

                background_sample = shap.kmeans(X_train_for_shap, 50)
                explainer = shap.KernelExplainer(best_estimator.named_steps['model'].predict, background_sample)
                shap_values = explainer.shap_values(X_test_for_shap)

            else:
                raise ValueError(f"Unknown model: {model_name}. The global_shap_values_calculator is calibrated to compute only SHAP values for regression models.")

            # SOURCE: https://stackoverflow.com/questions/77474923/calculate-the-mean-of-absolute-shap-values-across-all-classes 
            feature_importance_overall = np.mean(np.abs(shap_values), axis=0)

            ranking_df = pd.DataFrame({
                'Feature': feature_names,
                'Mean_Abs_SHAP': feature_importance_overall
                }).sort_values(by='Mean_Abs_SHAP', ascending=False).reset_index(drop=True)
        
            ranking_df['SHAP_Ranking'] = ranking_df.index + 1

        global_mean_absolute_shap_rankings[model_name] = ranking_df
        individual_shap_values_for_every_model[model_name] = {'shap_values': shap_values,'X_test_subset': X_test_for_shap if model_name in ["LR", "SVR"] else X_test}
    
    return global_mean_absolute_shap_rankings, individual_shap_values_for_every_model

def inter_model_concordance_assessment(shap_global_rankings_dic, top_k_features_concordance):
    """
    Assesses the inter-model concordance of feature rankings based on SHAP values.

    Arguments:
    - shap_global_rankings_dic (dict): A dictionary of global SHAP rankings for each model, from local_and_global_shap_values_calculator().
    - top_k_features_concordance (int): The number of top features to consider for concordance assessment.

    Returns:
    - pd.DataFrame: A DataFrame containing the concordance metrics (Kendall's tau and Spearman's rho, overlap ratio) for each model pair.
    """

    results=[]
    model_names = list(shap_global_rankings_dic.keys())

    for i in range(len(model_names)):
        for j in range(i + 1, len(model_names)):

            df_model_i = shap_global_rankings_dic[model_names[i]]
            df_model_j = shap_global_rankings_dic[model_names[j]]

            df_merged = pd.merge(df_model_i[['Feature','SHAP_Ranking']], df_model_j[['Feature','SHAP_Ranking']], on='Feature', suffixes=(f'_{model_names[i]}', f'_{model_names[j]}'))
            kendall_coeff, kendall_p_value = kendalltau(df_merged[f'SHAP_Ranking_{model_names[i]}'], df_merged[f'SHAP_Ranking_{model_names[j]}'])
            spearman_coeff, spearman_p_value = spearmanr(df_merged[f'SHAP_Ranking_{model_names[i]}'], df_merged[f'SHAP_Ranking_{model_names[j]}'])

            top_k_features_model_i = set(df_model_i.head(top_k_features_concordance)['Feature'])
            top_k_features_model_j = set(df_model_j.head(top_k_features_concordance)['Feature'])
            overlap_ratio = len(top_k_features_model_i & top_k_features_model_j) / top_k_features_concordance

            results.append({
                'Model 1': model_names[i],
                'Model 2': model_names[j],
                'Kendall_coeff': kendall_coeff,
                'Kendall p value': kendall_p_value,
                'Spearman coeff': spearman_coeff,
                'Spearman p value': spearman_p_value,
                'Overlap ratio': overlap_ratio
            })

    return pd.DataFrame(results)

def feature_agreement_stats(shap_global_rankings_dic):
    """
    Computes statistics on feature agreement across all models in the Rashomon set.

    Arguments:
    - shap_global_rankings_dic (dict): A dictionary of global SHAP rankings for each model, from local_and_global_shap_values_calculator().

    Returns:
    - pd.DataFrame: A DataFrame with mean and standard deviation of SHAP rankings for each feature. The global SHAP rankings for each model are also included.
    """

    model_names = list(shap_global_rankings_dic.keys())
    results = []

    for model in model_names:
        df_model = shap_global_rankings_dic[model]

        for _, row in df_model.iterrows():
            results.append({
                'Model': model,
                'Feature': row['Feature'],
                f"SHAP_Ranking": row['SHAP_Ranking']
            })

    results_df = pd.DataFrame(results)
    results_df = results_df.pivot(index='Feature', columns='Model', values='SHAP_Ranking')
    results_df = results_df.reset_index().rename_axis(columns=None)
    results_df = results_df.rename(columns={model: f"{model} SHAP RANKING" for model in model_names})

    shap_columns = [f"{model} SHAP RANKING" for model in model_names]
    results_df['Mean SHAP rank'] = results_df[shap_columns].mean(axis=1)
    results_df['Standard deviation SHAP rank'] = results_df[shap_columns].std(axis=1)
    results_df = results_df.sort_values(by='Mean SHAP rank', ascending=True)

    return results_df

def intra_model_stability_assessment(local_shap_dict, feature_names, n_iterations=500):
    """
    Assesses the intra-model stability of feature importance using bootstrapping with replacement on local SHAP values.

    Arguments:
    - local_shap_dict (dict): A dictionary with local SHAP values, from local_and_global_shap_values_calculator().
    - feature_names (list): A list of feature names.
    - n_iterations (int, optional): The number of bootstrap iterations. Defaults to 500.

    Returns:
    - dict: A dictionary of DataFrame, one for each model, with stability metrics for each feature.
    """
    # INSPIRATION: - https://stackoverflow.com/questions/21578917/simple-bootstrap-with-replacement-of-list 
    #              - https://www.askpython.com/python/examples/bootstrap-sampling-introduction 
    #              - https://www.pythonhealthdatascience.com/content/01_algorithms/03_numpy/08_cs1.html 

    # Reuse local SHAP values to avoid recomputing SHAP for every bootstrap
    bootstrap_results = {}

    
    for model_name in local_shap_dict:
        print(f"DEBUG: Model treatment: {model_name}")
        
        data = local_shap_dict[model_name]
        shap_matrix = data['shap_values']  
        
        n_samples = shap_matrix.shape[0]   
        n_features = shap_matrix.shape[1]  
        
        # Store feature importance for each bootstrap.
        all_estimations = np.zeros((n_iterations, n_features))

        for iteration in range(n_iterations):
            
            random_indices = []
            for _ in range(n_samples):
                index = np.random.randint(0, n_samples) 
                random_indices.append(index)

            bootstrap_sample = np.zeros((n_samples, n_features))
            for i in range(n_samples):
                index = random_indices[i]
                bootstrap_sample[i, :] = shap_matrix[index, :]
            
            importances = np.zeros(n_features)
            for feature in range(n_features):
                shap_values = bootstrap_sample[:, feature]
                absolute_shap_values = np.abs(shap_values)
                importances[feature] = np.mean(absolute_shap_values)
            
            all_estimations[iteration, :] = importances
        
        # For each feature, the mean of the mean importances obtained from each bootstrap iteration is computed.
        means_estimations = np.mean(all_estimations, axis=0)
        
        # For each feature, the standard deviation of the mean importances obtained from each bootstrap iteration is computed.
        standard_deviation = np.std(all_estimations, axis=0)
        
        # Coefficient of variation = standard deviation / mean
        cv = np.zeros(n_features)
        for feature in range(n_features):
            if means_estimations[feature] > 0:
                cv[feature] = standard_deviation[feature] / means_estimations[feature]
            else:
                cv[feature] = 0
        
        results = []
        for feature in range(n_features):
            results.append({
                'Feature': feature_names[feature],
                'Mean Global SHAP': means_estimations[feature],
                'Standard deviation of Global SHAP': standard_deviation[feature],
                'Coefficient of Variation': cv[feature]
            })
        
        df_results = pd.DataFrame(results)
        df_results = df_results.sort_values(by='Mean Global SHAP', ascending=False)
        df_results = df_results.reset_index(drop=True)
        
        bootstrap_results[model_name] = df_results
    
    return bootstrap_results

def assess_features_robustness(global_rankings_dict, intra_model_assessment_results, top_k):
    """
    Assesses feature robustness based on stability (CV) and importance (SHAP ranking) in the Rashomon set following the Model-Class Reliance (MCR) approach.

    Arguments:
     - global_rankings_dict (dict): A dictionary of global SHAP rankings for each model, from local_and_global_shap_values_calculator().
     - intra_model_assessment_results (dict): A dictionary of intra-model stability assessment results, from intra_model_stability_assessment().
     - top_k (int): The number of top features to consider for robustness assessment. 

    Returns:
     - pd.DataFrame: A DataFrame classifying features as robust and retained based on the assessment criteria. 
    """

    model_names = list(global_rankings_dict.keys())
    top_k_sets = []

    for model in model_names:
        top_k_feats = global_rankings_dict[model].sort_values(by='SHAP_Ranking', ascending=True).head(top_k)['Feature'].tolist()
        top_k_sets.append(set(top_k_feats))
    
    # MCR for Model-Class Reliance
    MCR_intersection = top_k_sets[0]
    for i in range(1, len(top_k_sets)):
        MCR_intersection = MCR_intersection.intersection(top_k_sets[i])

    # Mean of Abs SHAP per feature
    shap_scores = []
    for model, df in global_rankings_dict.items():
        for _, row in df.iterrows():
            shap_scores.append({
                'Feature': row['Feature'],
                'Mean_Abs_SHAP': row['Mean_Abs_SHAP']
            })

    shap_scores_df = pd.DataFrame(shap_scores)
    global_shap_df = shap_scores_df.groupby('Feature')['Mean_Abs_SHAP'].mean().reset_index()
    shap_dict = global_shap_df.set_index('Feature')['Mean_Abs_SHAP'].to_dict()

    cv_scores = []
    for model, results in intra_model_assessment_results.items():
        for _, row in results.iterrows():
            cv_scores.append({
                'Feature': row['Feature'],
                'Coefficient of Variation': row['Coefficient of Variation']
            })

    cv_scores_df = pd.DataFrame(cv_scores)
    
    # Mean of CV per feature
    global_cv_scores_df = cv_scores_df.groupby('Feature')['Coefficient of Variation'].mean().reset_index()

    final_classifications = []
    
    for _, row in global_cv_scores_df.iterrows():
        feature = row['Feature']
        mean_cv = row['Coefficient of Variation']
        mean_shap = shap_dict.get(feature, 0.0)
        
        stable = mean_cv <= 0.15
        in_top_k = feature in MCR_intersection
        retained = stable and in_top_k
        
        final_classifications.append({
            'Feature': feature,
            'Mean Absolute SHAP': mean_shap,
            'Mean CV': mean_cv,
            'CV stable': 'Yes' if stable else 'No',
            'In Top-K intersection': 'Yes' if in_top_k else 'No',
            'Retained': 'Yes' if retained else 'No'
        })

    final_classifications_df = pd.DataFrame(final_classifications)
    
    final_classifications_df['Retained_Sort'] = final_classifications_df['Retained'].apply(lambda x: 0 if x == 'Yes' else 1)
    final_classifications_df = final_classifications_df.sort_values(
        by=['Retained_Sort', 'Mean Absolute SHAP'], 
        ascending=[True, False]
    ).drop(columns=['Retained_Sort']).reset_index(drop=True)
    final_classifications_df.index = final_classifications_df.index + 1
    
    return final_classifications_df


    



    



        

    
        
